name: Node Continuous Integration

on:
  push:
    branches: 
      - master
      - testing

jobs:
 test_push_action:
    strategy:
# Use of matrix
     matrix:
      os:
      - ubuntu-latest
      - windows-latest
      node--version:
      - 8
      - 10
      - 12
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: ${{matrix.node-version}}
      - run: npm ci
      - run: npm test
      - run: npm run build
